variable "project_name" {}
variable "environment" {}
variable "account_id" {}
variable "ecs_cluster_name" {}
variable "ecs_cluster_arn" {}
variable "ecs_service_name" {}
variable "ecs_service_id" {}
variable "ecs_task_definition_family" {}
variable "alb_tg_name" {}